"""
Data classes for the clients.
"""

from dataclasses import dataclass, fields
from enum import Enum
from uuid import UUID


class MFAStatus(Enum):
    
    USED = 1
    """ The user used MFA when logging in. """
    
    NOT_USED = 2
    """ The user chose not to use MFA when logging in. """
    
    UNKNOWN = 3
    """
    Either
        * The 3rd party identity supplier does not support MFA or
        * The 3rd party identity supplier was configured not to use MFA or
        * The 3rd party identity supplier did not provide enough information to determine if
          MFA was used or
        * MFA is not applicable to the data (e.g. token types other than Login tokens).
    
    """
    
    @classmethod
    def get_mfa(cls, mfa: str):
        """ Given a string, get the mfa enum. """
        if not mfa:
            return cls.UNKNOWN
        mfa = mfa.lower() 
        if mfa not in _STR2MFA:
            raise ValueError("Unknown MFA string: " + mfa)
        return _STR2MFA[mfa]


_STR2MFA = {
    "used": MFAStatus.USED,
    "notused": MFAStatus.NOT_USED,
    "unknown": MFAStatus.UNKNOWN,
}


class TokenType(Enum):
    
    LOGIN = 1
    """ A login token, generated by the user going through a login flow. """
    
    AGENT = 2
    """
    An agent token generated from a login token. Intended for creation prior to running
    a job to prevent token expiration during the job.
    """
    
    DEVELOPER = 3
    """ Longer lived tokens intended for developer use of the system via API calls. """
    
    SERVICE = 4
    """ Very long lived tokens intended for services to communicate with each other. """

    @classmethod
    def get_type(cls, type_: str):
        """ Given a string, get the token enum. """
        if not type_:
            raise ValueError("type_ is required")
        type_ = type_.lower() 
        if type_ not in _STR2TYPE:
            raise ValueError("Unknown token type string: " + type_)
        return _STR2TYPE[type_]


_STR2TYPE = {
    "login": TokenType.LOGIN,
    "agent": TokenType.AGENT,
    "developer": TokenType.DEVELOPER,
    "service": TokenType.SERVICE,
}


@dataclass
class Token:
    """ A KBase authentication token. """
    id: UUID
    """ The token's unique ID. """
    user: str
    """ The username of the user associated with the token. """
    type: TokenType
    """ The type of the token. """
    mfa: MFAStatus
    """ The MFA status of the token. """
    created: int
    """ The time the token was created in epoch milliseconds. """
    expires: int
    """ The time the token expires in epoch milliseconds. """
    cachefor: int
    """ The time the token should be cached for in milliseconds. """


VALID_TOKEN_FIELDS: set[str] = {f.name for f in fields(Token)}
"""
The field names for the Token dataclass.
"""


@dataclass
class User:
    """ Information about a KBase user. """
    user: str
    """ The username of the user associated with the token. """
    customroles: list[str]
    """ The Auth2 custom roles the user possesses. """
    # Not seeing any other fields that are generally useful right now
    # Don't really want to expose idents unless there's a very good reason


VALID_USER_FIELDS: set[str] = {f.name for f in fields(User)}
"""
The field names for the User dataclass.
"""
